import type {
  Vehicle,
  Customer,
  Inspection,
  TeamMember,
  Challan,
  ExtraCharges,
} from '@/types/rental';

export const mockMembers: TeamMember[] = [
  { id: 'm1', name: 'Arjun Mehta', role: 'owner' },
  { id: 'm2', name: 'Priya Sharma', role: 'manager' },
  { id: 'm3', name: 'Vikram Singh', role: 'staff' },
];

export const mockVehicles: Vehicle[] = [
  {
    id: 'v1',
    registration_number: 'MH 01 AB 1234',
    brand: 'Maruti Suzuki',
    model: 'Swift Dzire',
    deposit_amount: 5000,
    extra_charge_per_km: 12,
    charge_per_extra_hour: 150,
    rate_per_fuel_point: 50,
    charge_rows: [
      { id: 'cr1', unit: 'hour', value: 1, price: 250, allowed_kms: 15 },
      { id: 'cr2', unit: 'hour', value: 4, price: 900, allowed_kms: 60 },
      { id: 'cr3', unit: 'day', value: 1, price: 1800, allowed_kms: 250 },
      { id: 'cr4', unit: 'day', value: 3, price: 4800, allowed_kms: 750 },
      { id: 'cr5', unit: 'week', value: 1, price: 12000, allowed_kms: 1750 },
    ],
  },
  {
    id: 'v2',
    registration_number: 'MH 02 CD 5678',
    brand: 'Hyundai',
    model: 'Creta',
    deposit_amount: 8000,
    extra_charge_per_km: 15,
    charge_per_extra_hour: 200,
    rate_per_fuel_point: 60,
    charge_rows: [
      { id: 'cr6', unit: 'hour', value: 1, price: 350, allowed_kms: 15 },
      { id: 'cr7', unit: 'hour', value: 4, price: 1200, allowed_kms: 60 },
      { id: 'cr8', unit: 'day', value: 1, price: 2500, allowed_kms: 250 },
      { id: 'cr9', unit: 'day', value: 3, price: 6500, allowed_kms: 750 },
      { id: 'cr10', unit: 'week', value: 1, price: 16000, allowed_kms: 1750 },
    ],
  },
  {
    id: 'v3',
    registration_number: 'MH 03 EF 9012',
    brand: 'Toyota',
    model: 'Innova',
    deposit_amount: 12000,
    extra_charge_per_km: 18,
    charge_per_extra_hour: 250,
    rate_per_fuel_point: 80,
    charge_rows: [
      { id: 'cr11', unit: 'hour', value: 1, price: 500, allowed_kms: 15 },
      { id: 'cr12', unit: 'hour', value: 4, price: 1800, allowed_kms: 60 },
      { id: 'cr13', unit: 'day', value: 1, price: 3500, allowed_kms: 250 },
      { id: 'cr14', unit: 'day', value: 3, price: 9000, allowed_kms: 750 },
      { id: 'cr15', unit: 'week', value: 1, price: 22000, allowed_kms: 1750 },
    ],
  },
];

export const mockCustomers: Customer[] = [
  {
    id: 'c1',
    name: 'Rahul Verma',
    phone: '9876543210',
    email: 'rahul.verma@email.com',
    aadhar_number: 'XXXX-XXXX-1234',
    dl_number: 'MH0420190001234',
    photo_url: null,
    dl_front_url: null,
    dl_back_url: null,
    aadhar_front_url: null,
    aadhar_back_url: null,
    pan_number: null,
    pan_front_url: null,
    pan_back_url: null,
  },
  {
    id: 'c2',
    name: 'Sneha Patel',
    phone: '9820011223',
    email: 'sneha.patel@email.com',
    aadhar_number: null,
    dl_number: null,
    photo_url: null,
    dl_front_url: null,
    dl_back_url: null,
    aadhar_front_url: null,
    aadhar_back_url: null,
    pan_number: null,
    pan_front_url: null,
    pan_back_url: null,
  },
];

const emptyExtra: ExtraCharges = {
  km_charge: 0,
  fuel_charge: 0,
  overdue_charge: 0,
  extra_kms: 0,
  fuel_shortfall: 0,
  extra_hours: 0,
};

export const mockInspections: Inspection[] = [
  {
    id: 'i1',
    rental_no: 'RNT-2026-001',
    car_id: 'v1',
    customer_id: 'c1',
    lifecycle_status: 'ISSUED',
    status: 'Before Pending',
    docstatus: 0,
    rental_start_date: '2026-09-15',
    rental_start_time: '10:00',
    rental_actual_start_time: '2026-09-15T10:00:00.000Z',
    rental_end_time: '2026-09-18T10:00:00.000Z',
    duration_days: 3,
    duration_hours: 0,
    planned_duration_minutes: 4320,
    actual_duration_minutes: null,
    rental_amount: 4800,
    deposit_amount: 5000,
    deposit_kind: 'money',
    deposit_paid: true,
    deposit_payment_status: 'PAID',
    deposit_payment_method: 'online',
    deposit_proof_url: 'mock://proof/issue-i1.png',
    issue_adjustment_amount: 300,
    issue_payment_method: 'online',
    issue_payment_proof_url: 'mock://proof/issue-i1.png',
    issue_payment_collector_id: null,
    issued_at: '2026-09-15T10:00:00.000Z',
    issued_by_member_id: 'm1',
    odometer_out: 15420,
    odometer_out_image_url: 'mock://odo-out/i1.png',
    fuel_points_out: 8,
    return_date: null,
    returned_at: null,
    rental_actual_end_time: null,
    odometer_return: null,
    odometer_return_image_url: null,
    fuel_points_return: null,
    damage_charge: 0,
    damage_image_url: null,
    returned_by_member_id: null,
    calculated_total: 0,
    discount_amount: 0,
    extra_charges: emptyExtra,
    total_to_pay: 0,
    payment_method: null,
    payment_proof_url: null,
    return_payment_collector_id: null,
    pledge_status: 'N/A',
    pledge_registration: null,
    pledge_make_model: null,
    pledge_colour: null,
    pledge_notes: null,
    pledge_photo_urls: null,
    pledge_rc_url: null,
    pledge_renter_photo_url: null,
    pledge_released_by_member_id: null,
    pledge_released_at: null,
    released_by_user_id: null,
    released_at: null,
    challans_synced_at_issue: true,
    challans_synced_at_return: false,
    confession_video_url: null,
    agreement_pdf_url: null,
  },
  {
    id: 'i2',
    rental_no: 'RNT-2026-002',
    car_id: 'v2',
    customer_id: 'c2',
    lifecycle_status: 'DRAFT',
    status: 'Draft',
    docstatus: 0,
    rental_start_date: '2026-09-17',
    rental_start_time: '09:00',
    rental_actual_start_time: null,
    rental_end_time: '2026-09-18T09:00:00.000Z',
    duration_days: 1,
    duration_hours: 0,
    planned_duration_minutes: 1440,
    actual_duration_minutes: null,
    rental_amount: 2500,
    deposit_amount: 0,
    deposit_kind: 'pledge',
    deposit_paid: false,
    deposit_payment_status: 'PENDING',
    deposit_payment_method: null,
    deposit_proof_url: null,
    issue_adjustment_amount: 0,
    issue_payment_method: null,
    issue_payment_proof_url: null,
    issue_payment_collector_id: null,
    issued_at: null,
    issued_by_member_id: null,
    odometer_out: null,
    odometer_out_image_url: null,
    fuel_points_out: null,
    return_date: null,
    returned_at: null,
    rental_actual_end_time: null,
    odometer_return: null,
    odometer_return_image_url: null,
    fuel_points_return: null,
    damage_charge: 0,
    damage_image_url: null,
    returned_by_member_id: null,
    calculated_total: 0,
    discount_amount: 0,
    extra_charges: emptyExtra,
    total_to_pay: 0,
    payment_method: null,
    payment_proof_url: null,
    return_payment_collector_id: null,
    pledge_status: 'N/A',
    pledge_registration: 'MH 05 GH 7777',
    pledge_make_model: 'Honda City',
    pledge_colour: 'White',
    pledge_notes: 'Customer pledge vehicle',
    pledge_photo_urls: ['mock://pledge/i2-1.png'],
    pledge_rc_url: 'mock://pledge/i2-rc.pdf',
    pledge_renter_photo_url: 'mock://pledge/i2-renter.png',
    pledge_released_by_member_id: null,
    pledge_released_at: null,
    released_by_user_id: null,
    released_at: null,
    challans_synced_at_issue: false,
    challans_synced_at_return: false,
    confession_video_url: null,
    agreement_pdf_url: null,
  },
  {
    id: 'i3',
    rental_no: 'RNT-2026-003',
    car_id: 'v3',
    customer_id: 'c1',
    lifecycle_status: 'RETURNED',
    status: 'Completed',
    docstatus: 1,
    rental_start_date: '2026-09-10',
    rental_start_time: '08:00',
    rental_actual_start_time: '2026-09-10T08:00:00.000Z',
    rental_end_time: '2026-09-11T08:00:00.000Z',
    duration_days: 1,
    duration_hours: 0,
    planned_duration_minutes: 1440,
    actual_duration_minutes: 1560,
    rental_amount: 3500,
    deposit_amount: 12000,
    deposit_kind: 'money',
    deposit_paid: true,
    deposit_payment_status: 'PAID',
    deposit_payment_method: 'cash',
    deposit_proof_url: null,
    issue_adjustment_amount: 0,
    issue_payment_method: 'cash',
    issue_payment_proof_url: null,
    issue_payment_collector_id: 'm2',
    issued_at: '2026-09-10T08:00:00.000Z',
    issued_by_member_id: 'm2',
    odometer_out: 42000,
    odometer_out_image_url: 'mock://odo-out/i3.png',
    fuel_points_out: 8,
    return_date: '2026-09-11',
    returned_at: '2026-09-11T10:00:00.000Z',
    rental_actual_end_time: '2026-09-11T10:00:00.000Z',
    odometer_return: 42280,
    odometer_return_image_url: 'mock://odo-ret/i3.png',
    fuel_points_return: 5,
    damage_charge: 500,
    damage_image_url: 'mock://damage/i3.png',
    returned_by_member_id: 'm3',
    calculated_total: 4490,
    discount_amount: 200,
    extra_charges: {
      km_charge: 540,
      fuel_charge: 240,
      overdue_charge: 500,
      extra_kms: 30,
      fuel_shortfall: 3,
      extra_hours: 2,
    },
    total_to_pay: 4790,
    payment_method: 'online',
    payment_proof_url: 'mock://proof/return-i3.png',
    return_payment_collector_id: null,
    pledge_status: 'N/A',
    pledge_registration: null,
    pledge_make_model: null,
    pledge_colour: null,
    pledge_notes: null,
    pledge_photo_urls: null,
    pledge_rc_url: null,
    pledge_renter_photo_url: null,
    pledge_released_by_member_id: null,
    pledge_released_at: null,
    released_by_user_id: null,
    released_at: null,
    challans_synced_at_issue: true,
    challans_synced_at_return: true,
    confession_video_url: null,
    agreement_pdf_url: null,
  },
];

export const mockChallans: Challan[] = [
  {
    id: 'ch1',
    vehicle_id: 'v1',
    inspection_id: 'i1',
    challan_no: 'ECH20260915001',
    challan_date_time: '2026-09-14T14:30:00.000Z',
    challan_status: 'Pending',
    fine_amount: 500,
    total_amount: 500,
    offence_details: 'Overspeeding',
    challan_place: 'Mumbai-Pune Highway',
    capture_stage: 'at_issue',
    captured_at: '2026-09-15T10:00:00.000Z',
    cleared: true,
    cleared_at: '2026-09-15T10:05:00.000Z',
  },
  {
    id: 'ch2',
    vehicle_id: 'v1',
    inspection_id: 'i1',
    challan_no: 'ECH20260916001',
    challan_date_time: '2026-09-16T11:00:00.000Z',
    challan_status: 'Pending',
    fine_amount: 1000,
    total_amount: 1000,
    offence_details: 'Wrong parking',
    challan_place: 'Andheri West',
    capture_stage: 'at_return',
    captured_at: '2026-09-16T12:00:00.000Z',
    cleared: false,
    cleared_at: null,
  },
  {
    id: 'ch3',
    vehicle_id: 'v3',
    inspection_id: 'i3',
    challan_no: 'ECH20260910001',
    challan_date_time: '2026-09-09T16:00:00.000Z',
    challan_status: 'Paid',
    fine_amount: 300,
    total_amount: 300,
    offence_details: 'No pollution certificate',
    challan_place: 'Bandra',
    capture_stage: 'at_issue',
    captured_at: '2026-09-10T08:00:00.000Z',
    cleared: true,
    cleared_at: '2026-09-10T08:10:00.000Z',
  },
];
